//! 레코드 태그 상수와 이름 조회.
//!
//! 태그는 **항상 원시 u16으로 보존**한다 — enum 강제 변환을 하지 않아
//! 새 태그가 등장해도 정보가 깨지지 않는다. 이 모듈은 디버깅/덤프용
//! 이름 조회만 제공한다. (한글문서파일형식 5.0 §3 데이터 레코드)

pub const HWPTAG_BEGIN: u16 = 0x010;

// ── DocInfo 레코드 ──────────────────────────────────────────────
pub const DOCUMENT_PROPERTIES: u16 = HWPTAG_BEGIN; // 0x10
pub const ID_MAPPINGS: u16 = HWPTAG_BEGIN + 1;
pub const BIN_DATA: u16 = HWPTAG_BEGIN + 2;
pub const FACE_NAME: u16 = HWPTAG_BEGIN + 3;
pub const BORDER_FILL: u16 = HWPTAG_BEGIN + 4;
pub const CHAR_SHAPE: u16 = HWPTAG_BEGIN + 5;
pub const TAB_DEF: u16 = HWPTAG_BEGIN + 6;
pub const NUMBERING: u16 = HWPTAG_BEGIN + 7;
pub const BULLET: u16 = HWPTAG_BEGIN + 8;
pub const PARA_SHAPE: u16 = HWPTAG_BEGIN + 9;
pub const STYLE: u16 = HWPTAG_BEGIN + 10;
pub const DOC_DATA: u16 = HWPTAG_BEGIN + 11;
pub const DISTRIBUTE_DOC_DATA: u16 = HWPTAG_BEGIN + 12;
pub const COMPATIBLE_DOCUMENT: u16 = HWPTAG_BEGIN + 14;
pub const LAYOUT_COMPATIBILITY: u16 = HWPTAG_BEGIN + 15;
pub const TRACKCHANGE: u16 = HWPTAG_BEGIN + 16;

// ── 본문(BodyText) 레코드 ───────────────────────────────────────
pub const PARA_HEADER: u16 = HWPTAG_BEGIN + 50; // 0x42
pub const PARA_TEXT: u16 = HWPTAG_BEGIN + 51;
pub const PARA_CHAR_SHAPE: u16 = HWPTAG_BEGIN + 52;
pub const PARA_LINE_SEG: u16 = HWPTAG_BEGIN + 53;
pub const PARA_RANGE_TAG: u16 = HWPTAG_BEGIN + 54;
pub const CTRL_HEADER: u16 = HWPTAG_BEGIN + 55;
pub const LIST_HEADER: u16 = HWPTAG_BEGIN + 56;
pub const PAGE_DEF: u16 = HWPTAG_BEGIN + 57;
pub const FOOTNOTE_SHAPE: u16 = HWPTAG_BEGIN + 58;
pub const PAGE_BORDER_FILL: u16 = HWPTAG_BEGIN + 59;
pub const SHAPE_COMPONENT: u16 = HWPTAG_BEGIN + 60;
pub const TABLE: u16 = HWPTAG_BEGIN + 61;
pub const SHAPE_COMPONENT_LINE: u16 = HWPTAG_BEGIN + 62;
pub const SHAPE_COMPONENT_RECTANGLE: u16 = HWPTAG_BEGIN + 63;
pub const SHAPE_COMPONENT_ELLIPSE: u16 = HWPTAG_BEGIN + 64;
pub const SHAPE_COMPONENT_ARC: u16 = HWPTAG_BEGIN + 65;
pub const SHAPE_COMPONENT_POLYGON: u16 = HWPTAG_BEGIN + 66;
pub const SHAPE_COMPONENT_CURVE: u16 = HWPTAG_BEGIN + 67;
pub const SHAPE_COMPONENT_OLE: u16 = HWPTAG_BEGIN + 68;
pub const SHAPE_COMPONENT_PICTURE: u16 = HWPTAG_BEGIN + 69;
pub const SHAPE_COMPONENT_CONTAINER: u16 = HWPTAG_BEGIN + 70;
pub const CTRL_DATA: u16 = HWPTAG_BEGIN + 71;
pub const EQEDIT: u16 = HWPTAG_BEGIN + 72;
pub const SHAPE_COMPONENT_TEXTART: u16 = HWPTAG_BEGIN + 74;
pub const FORM_OBJECT: u16 = HWPTAG_BEGIN + 75;
pub const MEMO_SHAPE: u16 = HWPTAG_BEGIN + 76;
pub const MEMO_LIST: u16 = HWPTAG_BEGIN + 77;
pub const FORBIDDEN_CHAR: u16 = HWPTAG_BEGIN + 78;
pub const CHART_DATA: u16 = HWPTAG_BEGIN + 79;
pub const TRACK_CHANGE: u16 = HWPTAG_BEGIN + 80;
pub const TRACK_CHANGE_AUTHOR: u16 = HWPTAG_BEGIN + 81;
pub const VIDEO_DATA: u16 = HWPTAG_BEGIN + 82;
pub const SHAPE_COMPONENT_UNKNOWN: u16 = HWPTAG_BEGIN + 99;

/// 덤프 출력용 태그 이름. 모르는 태그는 `None`.
pub fn tag_name(tag: u16) -> Option<&'static str> {
    Some(match tag {
        DOCUMENT_PROPERTIES => "DOCUMENT_PROPERTIES",
        ID_MAPPINGS => "ID_MAPPINGS",
        BIN_DATA => "BIN_DATA",
        FACE_NAME => "FACE_NAME",
        BORDER_FILL => "BORDER_FILL",
        CHAR_SHAPE => "CHAR_SHAPE",
        TAB_DEF => "TAB_DEF",
        NUMBERING => "NUMBERING",
        BULLET => "BULLET",
        PARA_SHAPE => "PARA_SHAPE",
        STYLE => "STYLE",
        DOC_DATA => "DOC_DATA",
        DISTRIBUTE_DOC_DATA => "DISTRIBUTE_DOC_DATA",
        COMPATIBLE_DOCUMENT => "COMPATIBLE_DOCUMENT",
        LAYOUT_COMPATIBILITY => "LAYOUT_COMPATIBILITY",
        TRACKCHANGE => "TRACKCHANGE",
        PARA_HEADER => "PARA_HEADER",
        PARA_TEXT => "PARA_TEXT",
        PARA_CHAR_SHAPE => "PARA_CHAR_SHAPE",
        PARA_LINE_SEG => "PARA_LINE_SEG",
        PARA_RANGE_TAG => "PARA_RANGE_TAG",
        CTRL_HEADER => "CTRL_HEADER",
        LIST_HEADER => "LIST_HEADER",
        PAGE_DEF => "PAGE_DEF",
        FOOTNOTE_SHAPE => "FOOTNOTE_SHAPE",
        PAGE_BORDER_FILL => "PAGE_BORDER_FILL",
        SHAPE_COMPONENT => "SHAPE_COMPONENT",
        TABLE => "TABLE",
        SHAPE_COMPONENT_LINE => "SHAPE_COMPONENT_LINE",
        SHAPE_COMPONENT_RECTANGLE => "SHAPE_COMPONENT_RECTANGLE",
        SHAPE_COMPONENT_ELLIPSE => "SHAPE_COMPONENT_ELLIPSE",
        SHAPE_COMPONENT_ARC => "SHAPE_COMPONENT_ARC",
        SHAPE_COMPONENT_POLYGON => "SHAPE_COMPONENT_POLYGON",
        SHAPE_COMPONENT_CURVE => "SHAPE_COMPONENT_CURVE",
        SHAPE_COMPONENT_OLE => "SHAPE_COMPONENT_OLE",
        SHAPE_COMPONENT_PICTURE => "SHAPE_COMPONENT_PICTURE",
        SHAPE_COMPONENT_CONTAINER => "SHAPE_COMPONENT_CONTAINER",
        CTRL_DATA => "CTRL_DATA",
        EQEDIT => "EQEDIT",
        SHAPE_COMPONENT_TEXTART => "SHAPE_COMPONENT_TEXTART",
        FORM_OBJECT => "FORM_OBJECT",
        MEMO_SHAPE => "MEMO_SHAPE",
        MEMO_LIST => "MEMO_LIST",
        FORBIDDEN_CHAR => "FORBIDDEN_CHAR",
        CHART_DATA => "CHART_DATA",
        TRACK_CHANGE => "TRACK_CHANGE",
        TRACK_CHANGE_AUTHOR => "TRACK_CHANGE_AUTHOR",
        VIDEO_DATA => "VIDEO_DATA",
        SHAPE_COMPONENT_UNKNOWN => "SHAPE_COMPONENT_UNKNOWN",
        _ => return None,
    })
}
